### PR TITLE
Selection Sort Algorithm in C++ 

### PR DESCRIPTION
**Pull request by kittusinghkumar**
Added Selection Sort Algorithm in C++

### CODE REVIEW

**Comment by kittusinghkumar** [comment]
Issue :  https://github.com/navdiya-nikunj/DSA-beginner-friendly/issues/22

**Review by navdiya-nikunj — COMMENTED** [review]
Make proper comments to understand code and you good to go
once done just mention me i will merge it

**Comment by kittusinghkumar** [comment]
> Make proper comments to understand code and you good to go once done just mention me i will merge it

Updated !! @navdiya-nikunj 
Kindly Accept

**Comment by navdiya-nikunj** [comment]
Well done thanks for your contribution

**Pull request merged**
