### PR TITLE
Created Heaps.md in DATA STRUCTURE folder

### PR DESCRIPTION
**Pull request by InquisitiveMe15**
Heaps.md contains useful and basic information about heap data structure.
Kindly merge it .

Thank you :)

### CODE REVIEW

**Comment by InquisitiveMe15** [comment]
Kindly add the lab **hactoberfest** to this repository or **hactoberfest-accepted** to this PR.

It seems you have added the label to this repo but the spelling is incorrect.

It is written incorrectly as **hectoberfest** instead of **hactoberfest**.

**Comment by InquisitiveMe15** [comment]
Issue is #66

**Comment by navdiya-nikunj** [comment]
Thanks for correction and thanks for your contribution

**Comment by navdiya-nikunj** [comment]
Once you done mention me

**Comment by InquisitiveMe15** [comment]
@navdiya-nikunj 
Done.

**Comment by InquisitiveMe15** [comment]
Thank you :)

**Pull request merged**
